# Numpy Basics 
Is the core library for scientific computing in Python. The central object is the multidimensional array. Allows the mathematical operation with arrays. Core package under the hood of the main libraries. 

In [2]:
import numpy as np
print(np.__version__)

1.25.2


In [8]:
a = np.array([1,2,3])
print(a)
print(a.shape) # Get the shape
print(a.dtype) # Get the type 
print(a.size) # Gets the total number of elements

[1 2 3]
(3,)
int64
3


In [9]:
# Assign Values:
print(a[0])
a[0] = 23
print(a)

1
[23  2  3]


In [10]:
# Mathematical Operations (Every element of a gets multiplied)
b = a * np.array([2,0,2])
print(b)

# Add an element to our list 
a = np.array([1,2,3]

[46  0  6]
