# Numpy Basics 
Is the core library for scientific computing in ML. The central object is the multidimensional array. Allows the mathematical operation with arrays.

In [4]:
import numpy as np
print(np.__version__)

1.25.2


In [11]:
#Creating an array:
a = np.array([1,2,3])
print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)

[1 2 3]
(3,)
int64
1
3


In [13]:
# Access different elements:
print(a[0])
a[0] = 10 
print(a)

1
[10  2  3]


In [14]:
b = a * np.array([2,0,2])
print(b)

[20  0  6]


In [18]:
# Differences between lists and arrays:
l = [1,2,3]
a = np.array([1,2,3])

# The append does not work with numpy:
l.append(4)
print(l)

# This is broadcasing and does not add another element:
a = a + np.array(4)
print(a)

# Multiplication in numpy 
a = a * 2
print(a)

# Square Root:
c = np.sqrt(a)
print(c) 

# Dot Product:


[1, 2, 3, 4]
[5 6 7]
[10 12 14]
[3.16227766 3.46410162 3.74165739]
